name: varsitygo_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  #firebase_core: ^2.27.0
  firebase_database: ^10.4.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  geolocator: ^9.0.2
  http: ^0.13.5
  firebase_core: ^2.25.3
  firebase_auth: ^4.16.1
  cloud_firestore: ^4.15.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash_bg.webp
    - assets/logo.png
    - assets/bus_a.png
    - assets/bus_b.jpg
    - assets/bus_c.jpg
    - assets/bus_d.jpg
    - assets/bus_e.jpg
    - assets/map_placeholder.jpg
    - assets/login_illustration.jpg
    - assets/google_logo.png
